function Y = f_postpro3d(mesh,X,field_type,varargin)
% F_POSTPRO3D ...
%--------------------------------------------------------------------------
% Y = F_POSTPRO3D(mesh,X,'W0','id_elem',id_elem);
% Y = F_POSTPRO3D(mesh,X,'W1','id_elem',id_elem);
% Y = F_POSTPRO3D(mesh,X,'W1','id_face',id_face);
% Y = F_POSTPRO3D(mesh,X,'W2','id_elem',id_elem);
% Y = F_POSTPRO3D(mesh,X,'W3','id_elem',id_elem);

%--------------------------------------------------------------------------
% This code is written by: H-K. Bui, 2023
% as a contribution to champ3d code.
%--------------------------------------------------------------------------
% champ3d is copyright (c) 2023 H-K. Bui.
% See LICENSE and CREDITS files in champ3d root directory for more information.
% Huu-Kien.Bui@univ-nantes.fr
% IREENA Lab - UR 4642, Nantes Universite'
%--------------------------------------------------------------------------

datin = [];
for i = 1:length(varargin)/2
    datin.(lower(varargin{2*i-1})) = varargin{2*i};
end

if ~isfield(datin,'id_elem')
    nbElem  = mesh.nbElem;
    id_elem = 1:nbElem;
else
    id_elem = datin.id_elem;
    nbElem  = length(id_elem);
end

if isfield(datin,'id_face')
    id_face = datin.id_face;
    nbFace  = length(id_face);
else
    id_face = [];
    nbFace  = 0;
end

%--------------------------------------------------------------------------
if ~isfield(datin,'coef')
    coef = 1;
else
    coef = datin.coef;
end

if length(coef) == 1
    coef = [coef 0 0; 0 coef 0; 0 0 coef];
end

matCoef = zeros(3,3,nbElem);
if length(size(coef)) == 2
    for i = 1:3
        for j = 1:3
            matCoef(i,j,:) = coef(i,j);
        end
    end
else
    % coef can take the form of matCoef
    matCoef = coef;
end

%--------------------------------------------------------------------------

if ~isfield(datin,'vector_field')
    vector_field = ones(3,nbElem);
else
    vector_field = datin.vector_field;
end


con = f_connexion(mesh.elem_type);

switch lower(field_type)
    case 'w0'
        Y = zeros(1,nbElem);
        for i = 1:con.nbNo_inEl
            Y(1,:) = Y(1,:) + ...
                f_multrowv(X(mesh.elem(i,id_elem)),...
                    mesh.cWn(i,id_elem).*squeeze(matCoef(1,1,:)).');
        end
    case 'w1'
        Y = zeros(3,nbElem);
        for i = 1:con.nbEd_inEl
            Y(1,:) = Y(1,:) + ...
                f_multrowv(X(mesh.edge_in_elem(i,id_elem)),...
                    mesh.cWe(1,i,id_elem).*matCoef(1,1,:) + ...
                    mesh.cWe(2,i,id_elem).*matCoef(1,2,:) + ...
                    mesh.cWe(3,i,id_elem).*matCoef(1,3,:) );
            Y(2,:) = Y(2,:) + ...
                f_multrowv(X(mesh.edge_in_elem(i,id_elem)),...
                    mesh.cWe(1,i,id_elem).*matCoef(2,1,:) + ...
                    mesh.cWe(2,i,id_elem).*matCoef(2,2,:) + ...
                    mesh.cWe(3,i,id_elem).*matCoef(2,3,:) );
            Y(3,:) = Y(3,:) + ...
                f_multrowv(X(mesh.edge_in_elem(i,id_elem)),...
                    mesh.cWe(1,i,id_elem).*matCoef(3,1,:) + ...
                    mesh.cWe(2,i,id_elem).*matCoef(3,2,:) + ...
                    mesh.cWe(3,i,id_elem).*matCoef(3,3,:) );
        end
    case 'w1_onface'
        Yx = zeros(1,nbFace);
        Yy = zeros(1,nbFace);
        Y  = zeros(2,nbFace);
        %--------------------------------------------------------------
        [face,id_face_sibc] = f_filterface(mesh.face(:,id_face));
        for i = 1:length(face)
            id_gface_sibc{i} = id_face(id_face_sibc{i});
        end
        %--------------------------------------------------------------
        for i = 1:length(face)
            [flatnode,flatface] = f_flatface(mesh.node,...
                                             mesh.face(:,id_gface_sibc{i}));
            if size(flatface,1) == 3
                mesh_sibc = f_mdstri(mesh.node,flatface);
            elseif size(flatface,1) == 4
                mesh_sibc = f_mdsquad(mesh.node,flatface);
            end
            mesh_sibc = f_intkit2d(mesh_sibc,'flatnode',flatnode);
            con_sibc = f_connexion(mesh_sibc.elem_type);
            %----------------------------------------------------------
            for j = 1:con_sibc.nbEd_inEl
                Yx(1,id_face_sibc{i}) = Yx(1,id_face_sibc{i}) + ...
                    f_multrowv(X(mesh.edge_in_face(j,id_gface_sibc{i})),...
                        mesh_sibc.cWe(1,j,:).*coef(1,1) + ...
                        mesh_sibc.cWe(2,j,:).*coef(1,2) );
                Yy(1,id_face_sibc{i}) = Yy(1,id_face_sibc{i}) + ...
                    f_multrowv(X(mesh.edge_in_face(j,id_gface_sibc{i})),...
                        mesh_sibc.cWe(1,j,:).*coef(2,1) + ...
                        mesh_sibc.cWe(2,j,:).*coef(2,2) );
            end 
        end
        Y(1,:) = Yx;
        Y(2,:) = Yy;
    case 'w2'
        Y = zeros(3,nbElem);
        for i = 1:con.nbFa_inEl
            Y(1,:) = Y(1,:) + ...
                f_multrowv(X(mesh.face_in_elem(i,id_elem)),...
                    mesh.cWf(1,i,id_elem).*matCoef(1,1,:) + ...
                    mesh.cWf(2,i,id_elem).*matCoef(1,2,:) + ...
                    mesh.cWf(3,i,id_elem).*matCoef(1,3,:) );
            Y(2,:) = Y(2,:) + ...
                f_multrowv(X(mesh.face_in_elem(i,id_elem)),...
                    mesh.cWf(1,i,id_elem).*matCoef(2,1,:) + ...
                    mesh.cWf(2,i,id_elem).*matCoef(2,2,:) + ...
                    mesh.cWf(3,i,id_elem).*matCoef(2,3,:) );
            Y(3,:) = Y(3,:) + ...
                f_multrowv(X(mesh.face_in_elem(i,id_elem)),...
                    mesh.cWf(1,i,id_elem).*matCoef(3,1,:) + ...
                    mesh.cWf(2,i,id_elem).*matCoef(3,2,:) + ...
                    mesh.cWf(3,i,id_elem).*matCoef(3,3,:) );
        end
    case 'w3'
    case 'vint_w1.vector_field'
        Xvec = zeros(3,nbElem);
%         for i = 1:con.nbEd_inEl
%             Xvec(1,:) = Xvec(1,:) + ...
%                 f_multrowv(X(mesh.edge_in_elem(i,id_elem)),...
%                     mesh.cWe(1,i,id_elem).*coef(1,1) + ...
%                     mesh.cWe(2,i,id_elem).*coef(1,2) + ...
%                     mesh.cWe(3,i,id_elem).*coef(1,3) );
%             Xvec(2,:) = Xvec(2,:) + ...
%                 f_multrowv(X(mesh.edge_in_elem(i,id_elem)),...
%                     mesh.cWe(1,i,id_elem).*coef(2,1) + ...
%                     mesh.cWe(2,i,id_elem).*coef(2,2) + ...
%                     mesh.cWe(3,i,id_elem).*coef(2,3) );
%             Xvec(3,:) = Xvec(3,:) + ...
%                 f_multrowv(X(mesh.edge_in_elem(i,id_elem)),...
%                     mesh.cWe(1,i,id_elem).*coef(3,1) + ...
%                     mesh.cWe(2,i,id_elem).*coef(3,2) + ...
%                     mesh.cWe(3,i,id_elem).*coef(3,3) );
%         end
        for iG = 1:con.nbG
            for i = 1:con.nbEd_inEl
                Xvec(1,:) = Xvec(1,:) + con.Weigh(iG).*mesh.detJ{iG}(1,id_elem) .* ...
                    f_multrowv(X(mesh.edge_in_elem(i,id_elem)),...
                        mesh.We{iG}(1,i,id_elem).*coef(1,1,:) + ...
                        mesh.We{iG}(2,i,id_elem).*coef(1,2,:) + ...
                        mesh.We{iG}(3,i,id_elem).*coef(1,3,:) );
                Xvec(2,:) = Xvec(2,:) + con.Weigh(iG).*mesh.detJ{iG}(1,id_elem) .* ...
                    f_multrowv(X(mesh.edge_in_elem(i,id_elem)),...
                        mesh.We{iG}(1,i,id_elem).*coef(2,1,:) + ...
                        mesh.We{iG}(2,i,id_elem).*coef(2,2,:) + ...
                        mesh.We{iG}(3,i,id_elem).*coef(2,3,:) );
                Xvec(3,:) = Xvec(3,:) + con.Weigh(iG).*mesh.detJ{iG}(1,id_elem) .* ...
                    f_multrowv(X(mesh.edge_in_elem(i,id_elem)),...
                        mesh.We{iG}(1,i,id_elem).*coef(3,1,:) + ...
                        mesh.We{iG}(2,i,id_elem).*coef(3,2,:) + ...
                        mesh.We{iG}(3,i,id_elem).*coef(3,3,:) );
            end
        end
        Y = (vector_field(1,:) .* Xvec(1,:) + ...
             vector_field(2,:) .* Xvec(2,:) + ...
             vector_field(3,:) .* Xvec(3,:));

    case 'w1.w1'
        for iG = 1:con.nbG
            for i = 1:con.nbEd_inEl
                Xvec(1,:) = Xvec(1,:) + con.Weigh(iG).*mesh.detJ{iG}(1,id_elem) .* ...
                    f_multrowv(X(mesh.edge_in_elem(i,id_elem)).*conj(X(mesh.edge_in_elem(i,id_elem))),...
                        mesh.We{iG}(1,i,id_elem).*mesh.We{iG}(1,i,id_elem).*coef(1,1,:) + ...
                        mesh.We{iG}(2,i,id_elem).*mesh.We{iG}(2,i,id_elem).*coef(1,2,:) + ...
                        mesh.We{iG}(3,i,id_elem).*mesh.We{iG}(3,i,id_elem).*coef(1,3,:) );
                Xvec(2,:) = Xvec(2,:) + con.Weigh(iG).*mesh.detJ{iG}(1,id_elem) .* ...
                    f_multrowv(X(mesh.edge_in_elem(i,id_elem).*conj(X(mesh.edge_in_elem(i,id_elem)))),...
                        mesh.We{iG}(1,i,id_elem).*mesh.We{iG}(1,i,id_elem).*coef(2,1,:) + ...
                        mesh.We{iG}(2,i,id_elem).*mesh.We{iG}(2,i,id_elem).*coef(2,2,:) + ...
                        mesh.We{iG}(3,i,id_elem).*mesh.We{iG}(3,i,id_elem).*coef(2,3,:) );
                Xvec(3,:) = Xvec(3,:) + con.Weigh(iG).*mesh.detJ{iG}(1,id_elem) .* ...
                    f_multrowv(X(mesh.edge_in_elem(i,id_elem).*conj(X(mesh.edge_in_elem(i,id_elem)))),...
                        mesh.We{iG}(1,i,id_elem).*mesh.We{iG}(1,i,id_elem).*coef(3,1,:) + ...
                        mesh.We{iG}(2,i,id_elem).*mesh.We{iG}(2,i,id_elem).*coef(3,2,:) + ...
                        mesh.We{iG}(3,i,id_elem).*mesh.We{iG}(3,i,id_elem).*coef(3,3,:) );
            end
        end
        Y = (vector_field(1,:) .* Xvec(1,:) + ...
             vector_field(2,:) .* Xvec(2,:) + ...
             vector_field(3,:) .* Xvec(3,:));
         
         
end

end




