clear
clc

%% main parameters
x_plate   = 100e-3;
y_plate   = 3e-3;
sig_plate = 40e3;
mur_plate = 1;
x_coil    = 10e-3;
y_coil    = 5e-3;
sig_coil  = 58e6;
agap      = 2e-3;
x_airbox  = x_plate * 2;
y_airbox  = x_plate * 2;
x_dom     = x_airbox/5;
y_dom     = y_airbox/5;
Imax      = 1000;
Jmax      = 1e6;
nb_turns  = 1;
fr        = 200e3;
Iphase    = 'IA'; 
Isign     = +1;
l_plate   = 100e-3; % length for 3d

tsig_coil  = f_make_ltensor('type','isotropic','value',sig_coil);
tsig_plate = f_make_ltensor('type','gtensor',...
    'main_value',sig_plate,'ort1_value',sig_plate,'ort2_value',sig_plate,...
    'main_dir',[0 0 1],'ort1_dir',[1 0 0],'ort2_dir',[0 1 0]);
%% Configuration 

%c3dobj = f_create_c3dobj();


%% build 1D mesh
msize  = 1;
c3dobj = [];
% ---
c3dobj = f_add_x(c3dobj,'id_x','xdom_l'   ,'d',x_dom                 ,'dnum',msize,'dtype','log-');
c3dobj = f_add_x(c3dobj,'id_x','xair_l'   ,'d',x_airbox/2 - x_plate/2,'dnum',msize,'dtype','log-');
c3dobj = f_add_x(c3dobj,'id_x','xplate_l' ,'d',x_plate/2  - x_coil/2 ,'dnum',msize,'dtype','log-');
c3dobj = f_add_x(c3dobj,'id_x','xcoil'    ,'d',x_coil                ,'dnum',msize,'dtype','log=');
c3dobj = f_add_x(c3dobj,'id_x','xplate_r' ,'d',x_plate/2  - x_coil/2 ,'dnum',msize,'dtype','log+');
c3dobj = f_add_x(c3dobj,'id_x','xair_r'   ,'d',x_airbox/2 - x_plate/2,'dnum',msize,'dtype','log+');
c3dobj = f_add_x(c3dobj,'id_x','xdom_r'   ,'d',x_dom                 ,'dnum',msize,'dtype','log+');
% ---
c3dobj = f_add_y(c3dobj,'id_y','ydom_b'   ,'d',y_dom   ,'dnum',msize,'dtype','log-');
c3dobj = f_add_y(c3dobj,'id_y','yair_b'   ,'d',y_airbox,'dnum',msize,'dtype','log-');
c3dobj = f_add_y(c3dobj,'id_y','yplate'   ,'d',y_plate ,'dnum',msize,'dtype','log-');
c3dobj = f_add_y(c3dobj,'id_y','y_agap'   ,'d',agap    ,'dnum',msize,'dtype','lin');
c3dobj = f_add_y(c3dobj,'id_y','ycoil'    ,'d',y_coil  ,'dnum',msize,'dtype','log=');
c3dobj = f_add_y(c3dobj,'id_y','yair_t'   ,'d',y_airbox,'dnum',msize,'dtype','log+');
c3dobj = f_add_y(c3dobj,'id_y','ydom_t'   ,'d',y_dom   ,'dnum',msize,'dtype','log+');
% ---
c3dobj = f_add_layer(c3dobj,'id_layer','lplate' ,'d',l_plate,'dnum',3,'dtype','lin');

%% build 2D mesh
c3dobj = f_add_mesh2d(c3dobj,'id_mesh2d','my_mesh2d',...
        'build_from','mesh1d',...
        'id_x', {'xdom_l','xair_l','xplate_l','xcoil','xplate_r','xair_r','xdom_r'},...
        'id_y', {'ydom_b','yair_b','yplate','y_agap','ycoil','yair_t','ydom_t'});

%% define dom2d
c3dobj = f_add_dom2d(c3dobj,'id_mesh2d','my_mesh2d',...
        'id_dom2d','plate', ...
        'id_x', {'xplate_l','xcoil','xplate_r'},...
        'id_y', {'yplate'});

c3dobj = f_add_dom2d(c3dobj,'id_mesh2d','my_mesh2d',...
        'id_dom2d','coil', ...
        'id_x', {'xcoil'},...
        'id_y', {'ycoil'});

c3dobj = f_add_dom2d(c3dobj,'id_mesh2d','my_mesh2d',...
        'id_dom2d','agap', ...
        'id_x', {'xplate_l','xcoil','xplate_r'},...
        'id_y', {'y_agap'});

%% build 3d mesh
c3dobj = f_add_mesh3d(c3dobj,'id_mesh3d','my_mesh3d','mesher','c3d_hexamesh',...
                       'id_mesh2d',{'my_mesh2d'},...
                       'id_mesh1d',[],...
                       'id_layer',{'lplate'});

%% define dom3d
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','plate', ...
                      'id_dom2d',{'plate'},'id_layer',{'lplate'});
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','coil', ...
                      'id_dom2d',{'coil'},'id_layer',{'lplate'});
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','agap', ...
                      'id_dom2d',{'agap'},'id_layer',{'lplate'});
c3dobj = f_add_dom3d(c3dobj,'defined_on','bound_face',...
                      'of_dom3d','coil', ...
                      'id_dom3d','coil_surface');
c3dobj = f_add_dom3d(c3dobj,'defined_on','interface',...
                      'of_dom3d',{'plate','agap'}, ...
                      'id_dom3d','plate_upface');
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','airbox', ...
                      'dom3d_equation',...
                      {['x <= max(x)+1e-9 & x >= min(x)-1e-9 &' ...
                        'y <= max(y)+1e-9 & y >= min(y)-1e-9 &' ...
                        'z <= max(z)+1e-9 & z >= min(z)-1e-9' ]});
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','airbox2');
%% build emdesign3d

c3dobj = f_add_emdesign3d(c3dobj,'id_emdesign3d','bm_01_3d',...
                                 'id_mesh3d','my_mesh3d',...
                                 'em_model','aphijw',...
                                 'frequency',fr);

c3dobj = f_add_econductor(c3dobj,'id_emdesign3d','bm_01_3d',...
                          'id_econductor','plate', ...
                          'id_dom3d','plate','sigma',tsig_plate);

c3dobj = f_add_mconductor(c3dobj,'id_emdesign3d','bm_01_3d',...
                          'id_mconductor','plate', ...
                          'id_dom3d','plate','mu_r',mur_plate);

c3dobj = f_add_econductor(c3dobj,'id_emdesign3d','bm_01_3d',...
                          'id_econductor','coil', ...
                          'id_dom3d','coil','sigma',tsig_coil);

c3dobj = f_add_open_jscoil(c3dobj,'id_emdesign3d','bm_01_3d',...
                            'id_dom3d','coil',...
                            'id_coil','coil01',...
                            'coil_mode','transmitter',...
                            'petrode_equation',{['z > max(z)-1e-9']},...
                            'netrode_equation',{['z < min(z)+1e-9']},...
                            'j_coil',Jmax);

c3dobj = f_add_nomesh(c3dobj,'id_emdesign3d','bm_01_3d',...
                          'id_nomesh','nm_coil', ...
                          'id_dom3d','airbox');

c3dobj = f_add_airbox(c3dobj,'id_emdesign3d','bm_01_3d',...
                          'id_airbox','airbox', ...
                          'id_dom3d','airbox','a_value',0);
%%
f_view_c3dobj(c3dobj,'id_emdesign3d','bm_01_3d',...
              'id_coil','coil01','face_color',f_color(2),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_dom3d','airbox','face_color',f_color(2),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_dom3d','airbox2','face_color',f_color(3),'alpha_value',0.5);  hold on
%%

c3dobj = f_solve_emdesign3d(c3dobj);

%%
f_view_edge(c3dobj.mesh3d.my_mesh3d.node,...
            c3dobj.mesh3d.my_mesh3d.edge(:,c3dobj.emdesign3d.bm_01_3d.nomesh.nm_coil.aphijw.id_inner_edge),...
            'edge_color','r');

f_view_edge(c3dobj.mesh3d.my_mesh3d.node,...
            c3dobj.mesh3d.my_mesh3d.edge(:,c3dobj.emdesign3d.bm_01_3d.airbox.airbox.aphijw.id_inner_edge),...
            'edge_color','b');
f_view_edge(c3dobj.mesh3d.my_mesh3d.node,...
            c3dobj.mesh3d.my_mesh3d.edge(:,c3dobj.emdesign3d.bm_01_3d.airbox.airbox.aphijw.id_bound_edge),...
            'edge_color','k');








