clear
clc

%% main parameters
x_plate   = 100e-3;
y_plate   = 100e-3;
x_coil    = 20e-3;
y_coil    = 20e-3;
h_coil    = 100e-3;
t_coil    = 5e-3;
agap      = 2e-3;
ag_coil   = 2e-3;
ag_plate  = 1e-3;
x_airbox  = x_plate * 2;
y_airbox  = x_plate * 2;
h_airbox  = h_coil;
Imax      = 1000;
Jmax      = 1e6;
nb_turns  = 1;
fr        = 200e3;
h_plate_t = 1e-3;
h_plate_b = 2e-3;
% ---
sigma_coil    = 58e6;
sigma_plate_t = f_make_ltensor('type','ltensor',...
    'main_value',1e4,'ort1_value',1e4,'ort2_value',10,...
    'main_dir',[1 0 0],'ort1_dir',[0 1 0],'ort2_dir',[0 0 1]);
mur_plate_t   = 10;
sigma_plate_b = 1e6;
mur_plate_b   = f_make_ltensor('type','ltensor',...
    'main_value',10,'ort1_value',10,'ort2_value',1e3,...
    'main_dir',[1 0 0],'ort1_dir',[0 1 0],'ort2_dir',[0 0 1]);
% ---
br_dir = f_make_coef('f',@fbr_dir,'depend_on','c3dobj.mesh3d.my_mesh3d.cnode');
br_value = 1;

%% Configuration 

%c3dobj = f_create_c3dobj();


%% build 1D mesh
msize  = 3;
c3dobj = [];
% ---
c3dobj = f_add_x(c3dobj,'id_x','xair_l'   ,'d',x_airbox/2 - x_plate/2,'dnum',msize,'dtype','log-');
c3dobj = f_add_x(c3dobj,'id_x','xplate_l' ,'d',x_plate/2  - x_coil/2 ,'dnum',msize,'dtype','log-');
c3dobj = f_add_x(c3dobj,'id_x','xcoil_l'  ,'d',t_coil                ,'dnum',msize,'dtype','lin');
c3dobj = f_add_x(c3dobj,'id_x','xcoil_c'  ,'d',x_coil     - 2*t_coil ,'dnum',msize,'dtype','lin');
c3dobj = f_add_x(c3dobj,'id_x','xcoil_r'  ,'d',t_coil                ,'dnum',msize,'dtype','lin');
c3dobj = f_add_x(c3dobj,'id_x','xplate_r' ,'d',x_plate/2  - x_coil/2 ,'dnum',msize,'dtype','log+');
c3dobj = f_add_x(c3dobj,'id_x','xair_r'   ,'d',x_airbox/2 - x_plate/2,'dnum',msize,'dtype','log+');
% ---
c3dobj = f_add_y(c3dobj,'id_y','yair_l'   ,'d',y_airbox/2 - y_plate/2,'dnum',msize,'dtype','log-');
c3dobj = f_add_y(c3dobj,'id_y','yplate_l' ,'d',y_plate/2  - y_coil/2 ,'dnum',msize,'dtype','log-');
c3dobj = f_add_y(c3dobj,'id_y','ycoil_l'  ,'d',t_coil                ,'dnum',msize,'dtype','lin');
c3dobj = f_add_y(c3dobj,'id_y','ycoil_c'  ,'d',y_coil     - 2*t_coil ,'dnum',msize,'dtype','lin');
c3dobj = f_add_y(c3dobj,'id_y','ycoil_r'  ,'d',t_coil                ,'dnum',msize,'dtype','lin');
c3dobj = f_add_y(c3dobj,'id_y','yplate_r' ,'d',y_plate/2  - y_coil/2 ,'dnum',msize,'dtype','log+');
c3dobj = f_add_y(c3dobj,'id_y','yair_r'   ,'d',y_airbox/2 - y_plate/2,'dnum',msize,'dtype','log+');
% ---
c3dobj = f_add_layer(c3dobj,'id_layer','lair_b'   ,'d',h_airbox,'dnum',msize,'dtype','log-');
c3dobj = f_add_layer(c3dobj,'id_layer','lplate_b' ,'d',h_plate_b,'dnum',msize,'dtype','lin');
c3dobj = f_add_layer(c3dobj,'id_layer','lag_plate','d',ag_plate,'dnum',msize,'dtype','lin');
c3dobj = f_add_layer(c3dobj,'id_layer','lplate_t' ,'d',h_plate_t,'dnum',msize,'dtype','lin');
c3dobj = f_add_layer(c3dobj,'id_layer','lagap'    ,'d',agap,'dnum',msize,'dtype','lin');
c3dobj = f_add_layer(c3dobj,'id_layer','ltcoil_b' ,'d',t_coil,'dnum',msize,'dtype','lin');
c3dobj = f_add_layer(c3dobj,'id_layer','lag_coil' ,'d',ag_coil,'dnum',msize,'dtype','lin');
c3dobj = f_add_layer(c3dobj,'id_layer','ltcoil_t' ,'d',t_coil,'dnum',msize,'dtype','lin');
c3dobj = f_add_layer(c3dobj,'id_layer','lhcoil'   ,'d',h_coil,'dnum',msize,'dtype','log=');
%% build 2D mesh
c3dobj = f_add_mesh2d(c3dobj,'id_mesh2d','my_mesh2d',...
        'build_from','mesh1d',...
        'id_x', {'xair_l','xplate_l','xcoil_l','xcoil_c','xcoil_r','xplate_r','xair_r'},...
        'id_y', {'yair_l','yplate_l','ycoil_l','ycoil_c','ycoil_r','yplate_r','yair_r'});

%% define dom2d
c3dobj = f_add_dom2d(c3dobj,'id_mesh2d','my_mesh2d',...
        'id_dom2d','plate', ...
        'id_x', {'xplate_l','xcoil_l','xcoil_c','xcoil_r','xplate_r'},...
        'id_y', {'yplate_l','ycoil_l','ycoil_c','ycoil_r','yplate_r'});

c3dobj = f_add_dom2d(c3dobj,'id_mesh2d','my_mesh2d',...
        'id_dom2d','coil', ...
        'id_x', {{'xcoil_l','xcoil_r'},'xcoil_c',},...
        'id_y', {{'ycoil_l','ycoil_c','ycoil_r'},{'ycoil_l','ycoil_r'}});

c3dobj = f_add_dom2d(c3dobj,'id_mesh2d','my_mesh2d',...
        'id_dom2d','pmagnet', ...
        'id_x', {'xcoil_c'},...
        'id_y', {'ycoil_c'});
    
c3dobj = f_add_dom2d(c3dobj,'id_mesh2d','my_mesh2d',...
        'id_dom2d','etrode', ...
        'id_x', {'xcoil_l','xcoil_r'},...
        'id_y', {'ycoil_l'});

%% View 2d mesh

figure
f_view_c3dobj(c3dobj,'id_mesh2d','my_mesh2d',...
              'id_dom2d','plate','face_color',f_color(1),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_mesh2d','my_mesh2d',...
              'id_dom2d','coil','face_color',f_color(2),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_mesh2d','my_mesh2d',...
              'id_dom2d','pmagnet','face_color',f_color(3),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_mesh2d','my_mesh2d',...
              'id_dom2d','etrode','face_color',f_color(4),'alpha_value',0.5);  hold on

%% build 3d mesh
c3dobj = f_add_mesh3d(c3dobj,'id_mesh3d','my_mesh3d','mesher','c3d_hexamesh',...
                       'id_mesh2d',{'my_mesh2d'},...
                       'id_mesh1d',[],...
                       'id_layer',{'lair_b','lplate_b','lag_plate','lplate_t','lagap','ltcoil_b','lag_coil','ltcoil_t','lhcoil'});

%% define dom3d
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','plate_b', ...
                      'id_dom2d',{'plate'},'id_layer',{'lplate_b'});
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','plate_t', ...
                      'id_dom2d',{'plate'},'id_layer',{'lplate_t'});
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','close_coil_tx', ...
                      'id_dom2d',{'coil'},'id_layer',{'ltcoil_t'});
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','close_coil_rx', ...
                      'id_dom2d',{'coil'},'id_layer',{'ltcoil_b'});
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','open_coil', ...
                      'id_dom2d',{{'coil'},{'etrode'}},'id_layer',{'ltcoil_b',{'lag_coil','ltcoil_t','lhcoil'}});
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','pmagnet', ...
                      'id_dom2d',{'pmagnet'},'id_layer',{'ltcoil_b','lag_coil','ltcoil_t'});
c3dobj = f_add_dom3d(c3dobj,'defined_on','bound_face',...
                      'of_dom3d','open_coil', ...
                      'id_dom3d','open_coil_surface');
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','small_airbox', ...
                      'id_dom2d',{'plate'},'id_layer',{'l...'});
c3dobj = f_add_dom3d(c3dobj,'id_dom3d','big_airbox');

%% View 3d mesh
figure
f_view_c3dobj(c3dobj,'id_dom3d','plate_b','face_color',f_color(1),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_dom3d','plate_t','face_color',f_color(2),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_dom3d','close_coil_tx','face_color',f_color(3),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_dom3d','close_coil_rx','face_color',f_color(4),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_dom3d','open_coil','face_color',f_color(5),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_dom3d','pmagnet','face_color',f_color(6),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_dom3d','open_coil_surface','face_color',f_color(7),'alpha_value',0.5);  hold on
%f_view_c3dobj(c3dobj,'id_dom3d','small_airbox','face_color',f_color(8),'alpha_value',0.5);  hold on
%f_view_c3dobj(c3dobj,'id_dom3d','big_airbox','face_color',f_color(9),'alpha_value',0.5);  hold on


%% build emdesign3d em_test_open_js
c3dobj = f_add_emdesign3d(c3dobj,'id_emdesign3d','em_test_open_js',...
                                 'id_mesh3d','my_mesh3d',...
                                 'em_model','aphijw',...
                                 'frequency',fr);
% ---
c3dobj = f_add_econductor(c3dobj,'id_emdesign3d','em_test_open_js',...
                          'id_econductor','plate_t', ...
                          'id_dom3d','plate_t','sigma',sigma_plate_t);
% ---
c3dobj = f_add_econductor(c3dobj,'id_emdesign3d','em_test_open_js',...
                          'id_econductor','plate_b', ...
                          'id_dom3d','plate_b','sigma',sigma_plate_b);
% ---
c3dobj = f_add_mconductor(c3dobj,'id_emdesign3d','em_test_open_js',...
                          'id_mconductor','plate_b', ...
                          'id_dom3d','plate_b','mu_r',mur_plate_b);
% ---
c3dobj = f_add_pmagnet(c3dobj,'id_emdesign3d','em_test_open_js',...
                          'id_pmagnet','pmagnet', ...
                          'id_dom3d','pmagnet',...
                          'br_dir',br_dir,...
                          'br_value',br_value);
% ---
xcen_coil = x_airbox/2;
c3dobj = f_add_open_jscoil(c3dobj,'id_emdesign3d','em_test_open_js',...
                            'id_dom3d','open_coil',...
                            'id_coil','open_js',...
                            'coil_mode','transmitter',...
                            'petrode_equation',{['z >= max(z)-1e-9 & x > ' num2str(xcen_coil)]},...
                            'netrode_equation',{['z >= max(z)-1e-9 & x < ' num2str(xcen_coil)]},...
                            'j_coil',Jmax);
% ---
c3dobj = f_add_airbox(c3dobj,'id_emdesign3d','em_test_open_js',...
                          'id_airbox','small_airbox', ...
                          'id_dom3d','small_airbox','a_value',0);
% ---
figure
f_view_c3dobj(c3dobj,'id_emdesign3d','em_test_open_js',...
   'id_coil','open_js','face_color',f_color(1),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_emdesign3d','em_test_open_js',...
   'id_econductor','plate_t','face_color',f_color(2),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_emdesign3d','em_test_open_js',...
   'id_econductor','plate_b','face_color',f_color(3),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_emdesign3d','em_test_open_js',...
   'id_mconductor','plate_b','face_color',f_color(4),'alpha_value',0.5);  hold on
% ---
c3dobj = f_solve_emdesign3d(c3dobj,'id_emdesign3d','em_test_open_js');



return
%% build emdesign3d em_test_pmagnet
c3dobj = f_add_emdesign3d(c3dobj,'id_emdesign3d','em_test_pmagnet',...
                                 'id_mesh3d','my_mesh3d',...
                                 'em_model','aphits');
%% build emdesign3d em_test_open_is
c3dobj = f_add_emdesign3d(c3dobj,'id_emdesign3d','em_test_open_is',...
                                 'id_mesh3d','my_mesh3d',...
                                 'em_model','aphijw',...
                                 'frequency',fr);


%%
f_view_c3dobj(c3dobj,'id_emdesign3d','bm_01_3d',...
              'id_coil','coil01','face_color',f_color(2),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_dom3d','airbox','face_color',f_color(2),'alpha_value',0.5);  hold on
f_view_c3dobj(c3dobj,'id_dom3d','airbox2','face_color',f_color(3),'alpha_value',0.5);  hold on
%%

c3dobj = f_solve_emdesign3d(c3dobj);

%%
f_view_edge(c3dobj.mesh3d.my_mesh3d.node,...
            c3dobj.mesh3d.my_mesh3d.edge(:,c3dobj.emdesign3d.bm_01_3d.nomesh.nm_coil.aphijw.id_inner_edge),...
            'edge_color','r');

f_view_edge(c3dobj.mesh3d.my_mesh3d.node,...
            c3dobj.mesh3d.my_mesh3d.edge(:,c3dobj.emdesign3d.bm_01_3d.airbox.airbox.aphijw.id_inner_edge),...
            'edge_color','b');
f_view_edge(c3dobj.mesh3d.my_mesh3d.node,...
            c3dobj.mesh3d.my_mesh3d.edge(:,c3dobj.emdesign3d.bm_01_3d.airbox.airbox.aphijw.id_bound_edge),...
            'edge_color','k');








