clear
clc

nb_elem = 1e5;
coef_array1 = 2.*ones(3,3,nb_elem);
coef_array2 = 2.*ones(nb_elem,3,3);
nbG = 8;
nbEd_inEl = 12;

Weigh = [1 1 1];
detJ{1} = 2.*ones(1,nb_elem);
We1{1} = 4.*ones(3,nbEd_inEl,nb_elem);
We2{1} = 4.*ones(nb_elem,3,nbEd_inEl);

coefwewe1 = zeros(nbEd_inEl,nb_elem,nbEd_inEl);
coefwewe2 = zeros(nbEd_inEl,nb_elem,nbEd_inEl);
coefwewe3 = zeros(nbEd_inEl,nb_elem,nbEd_inEl);
coefwewe4 = zeros(nb_elem,nbEd_inEl,nbEd_inEl);
%--------------------------------------------------------------------------
tic
for iG = 1:1
    for i = 1:nbEd_inEl
        for j = i:nbEd_inEl % !!! i
            coefwewe1(i,:,j) = coefwewe1(i,:,j) + ...
                f_multrowv(Weigh(iG) .* detJ{iG},...
                coef_array1(1,1,:).*We1{iG}(1,i,:).*We1{iG}(1,j,:)+...
                coef_array1(1,2,:).*We1{iG}(2,i,:).*We1{iG}(1,j,:)+...
                coef_array1(1,3,:).*We1{iG}(3,i,:).*We1{iG}(1,j,:)+...
                coef_array1(2,1,:).*We1{iG}(1,i,:).*We1{iG}(2,j,:)+...
                coef_array1(2,2,:).*We1{iG}(2,i,:).*We1{iG}(2,j,:)+...
                coef_array1(2,3,:).*We1{iG}(3,i,:).*We1{iG}(2,j,:)+...
                coef_array1(3,1,:).*We1{iG}(1,i,:).*We1{iG}(3,j,:)+...
                coef_array1(3,2,:).*We1{iG}(2,i,:).*We1{iG}(3,j,:)+...
                coef_array1(3,3,:).*We1{iG}(3,i,:).*We1{iG}(3,j,:));
        end
    end
end
toc
%--------------------------------------------------------------------------
tic
for iG = 1:1
    for i = 1:nbEd_inEl
        for j = i:nbEd_inEl % !!! i
            coefwewe2(i,:,j) = coefwewe2(i,:,j) + ...
                Weigh(iG) .* detJ{iG} .* (squeeze(...
                coef_array1(1,1,:).*We1{iG}(1,i,:).*We1{iG}(1,j,:)+...
                coef_array1(1,2,:).*We1{iG}(2,i,:).*We1{iG}(1,j,:)+...
                coef_array1(1,3,:).*We1{iG}(3,i,:).*We1{iG}(1,j,:)+...
                coef_array1(2,1,:).*We1{iG}(1,i,:).*We1{iG}(2,j,:)+...
                coef_array1(2,2,:).*We1{iG}(2,i,:).*We1{iG}(2,j,:)+...
                coef_array1(2,3,:).*We1{iG}(3,i,:).*We1{iG}(2,j,:)+...
                coef_array1(3,1,:).*We1{iG}(1,i,:).*We1{iG}(3,j,:)+...
                coef_array1(3,2,:).*We1{iG}(2,i,:).*We1{iG}(3,j,:)+...
                coef_array1(3,3,:).*We1{iG}(3,i,:).*We1{iG}(3,j,:))).';
        end
    end
end
toc
%--------------------------------------------------------------------------
tic
for iG = 1:1
    for i = 1:nbEd_inEl
        for j = i:nbEd_inEl % !!! i
            weix = squeeze(We1{iG}(1,i,:));
            weiy = squeeze(We1{iG}(2,i,:));
            weiz = squeeze(We1{iG}(3,i,:));
            wejx = squeeze(We1{iG}(1,j,:));
            wejy = squeeze(We1{iG}(2,j,:));
            wejz = squeeze(We1{iG}(3,j,:));
            dJ   = detJ{iG};
            weigh= Weigh(iG);
            coefwewe3(i,:,j) = coefwewe3(i,:,j) + ...
                (weigh .* dJ.' .* (...
                squeeze(coef_array1(1,1,:)) .* weix .* wejx+...
                squeeze(coef_array1(1,2,:)) .* weiy .* wejx+...
                squeeze(coef_array1(1,3,:)) .* weiz .* wejx+...
                squeeze(coef_array1(2,1,:)) .* weix .* wejy+...
                squeeze(coef_array1(2,2,:)) .* weiy .* wejy+...
                squeeze(coef_array1(2,3,:)) .* weiz .* wejy+...
                squeeze(coef_array1(3,1,:)) .* weix .* wejz+...
                squeeze(coef_array1(3,2,:)) .* weiy .* wejz+...
                squeeze(coef_array1(3,3,:)) .* weiz .* wejz )).';
        end
    end
end
toc
%--------------------------------------------------------------------------
tic
for iG = 1:1
    for i = 1:nbEd_inEl
        for j = i:nbEd_inEl % !!! i
            weix = We2{iG}(:,1,i);
            weiy = We2{iG}(:,2,i);
            weiz = We2{iG}(:,3,i);
            wejx = We2{iG}(:,1,j);
            wejy = We2{iG}(:,2,j);
            wejz = We2{iG}(:,3,j);
            dJ   = f_tocolv(detJ{iG});
            weigh= Weigh(iG);
            coefwewe4(:,i,j) = coefwewe4(:,i,j) + ...
                weigh .* dJ .* (...
                coef_array2(:,1,1) .* weix .* wejx +...
                coef_array2(:,1,2) .* weiy .* wejx +...
                coef_array2(:,1,3) .* weiz .* wejx +...
                coef_array2(:,2,1) .* weix .* wejy +...
                coef_array2(:,2,2) .* weiy .* wejy +...
                coef_array2(:,2,3) .* weiz .* wejy +...
                coef_array2(:,3,1) .* weix .* wejz +...
                coef_array2(:,3,2) .* weiy .* wejz +...
                coef_array2(:,3,3) .* weiz .* wejz );
        end
    end
end
toc
%--------------------------------------------------------------------------
tic
coefwewe4 = sparse(coefwewe4);
toc
