c3dobj = f_add_dom3d(c3dobj,'defined_on','interface',...
                      'of_dom3d',{{'plate','coil'},'agap'}, ...
                      'id_dom3d','plate_upface');
                  
f_view_c3dobj(c3dobj,'id_mesh3d','my_mesh3d',...
              'id_dom3d','plate_upface','face_color',f_color(2),'alpha_value',0.5);  hold on