function f_chlogo()
%--------------------------------------------------------------------------
% This code is written by: H-K. Bui, 2023
% as a contribution to champ3d code.
%--------------------------------------------------------------------------
% champ3d is copyright (c) 2023 H-K. Bui.
% See LICENSE and CREDITS files in champ3d root directory for more information.
% Huu-Kien.Bui@univ-nantes.fr
% IREENA Lab - UR 4642, Nantes Universite'
%--------------------------------------------------------------------------

c3name = '$\overrightarrow{champ}{3d}$';
texpos = get(gca, 'OuterPosition');
hold on;
text(texpos(1),texpos(2)+1.05, ...
     c3name, ...
     'FontSize',10, ...
     'FontWeight','bold',...
     'Color','blue', ...
     'Interpreter','latex',...
     'Units','normalized', ...
     'VerticalAlignment', 'baseline', ...
     'HorizontalAlignment', 'right');



